// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using tod.Models;

#nullable disable

namespace tod.Migrations
{
    [DbContext(typeof(TodoContext))]
    partial class ContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("tod.Models.Category", b =>
                {
                    b.Property<string>("categoryId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("categoryName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("categoryId");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            categoryId = "personal",
                            categoryName = "Personal"
                        },
                        new
                        {
                            categoryId = "work",
                            categoryName = "Work"
                        },
                        new
                        {
                            categoryId = "school",
                            categoryName = "School"
                        },
                        new
                        {
                            categoryId = "relationship",
                            categoryName = "Relationship"
                        },
                        new
                        {
                            categoryId = "health",
                            categoryName = "Health"
                        },
                        new
                        {
                            categoryId = "finance",
                            categoryName = "Finance"
                        },
                        new
                        {
                            categoryId = "other",
                            categoryName = "Other"
                        });
                });

            modelBuilder.Entity("tod.Models.Status", b =>
                {
                    b.Property<string>("statusId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("statusName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("statusId");

                    b.ToTable("Statuses");

                    b.HasData(
                        new
                        {
                            statusId = "pending",
                            statusName = "Pending"
                        },
                        new
                        {
                            statusId = "completed",
                            statusName = "Completed"
                        });
                });

            modelBuilder.Entity("tod.Models.Tod", b =>
                {
                    b.Property<int>("todId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("todId"));

                    b.Property<string>("categoryId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("dueDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("statusId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("todDescription")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("todName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("todId");

                    b.HasIndex("categoryId");

                    b.HasIndex("statusId");

                    b.ToTable("Todos");
                });

            modelBuilder.Entity("tod.Models.Tod", b =>
                {
                    b.HasOne("tod.Models.Category", "Category")
                        .WithMany()
                        .HasForeignKey("categoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("tod.Models.Status", "Status")
                        .WithMany()
                        .HasForeignKey("statusId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");

                    b.Navigation("Status");
                });
#pragma warning restore 612, 618
        }
    }
}
